name: Release Parent POM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
      next-version:
        description: 'Next development version (e.g., 1.0.1-SNAPSHOT)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Create release branch
        run: |
          git checkout -b release-${{ github.event.inputs.version }}

      - name: Update version for release
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.version }} -DgenerateBackupPoms=false
          git add pom.xml
          git commit -m "Release version ${{ github.event.inputs.version }}"

      - name: Build and verify
        run: mvn clean verify

      - name: Create tag
        run: |
          git tag -a v${{ github.event.inputs.version }} -m "Release version ${{ github.event.inputs.version }}"

      - name: Update to next development version
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.next-version }} -DgenerateBackupPoms=false
          git add pom.xml
          git commit -m "Prepare for next development version ${{ github.event.inputs.next-version }}"

      - name: Push release branch and tag
        run: |
          git push --set-upstream origin release-${{ github.event.inputs.version }}
          git push --tags

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: release-${{ github.event.inputs.version }}
          title: "Release version ${{ github.event.inputs.version }}"
          body: |
            This PR:
            1. Updates version to ${{ github.event.inputs.version }}
            2. Tags this release as v${{ github.event.inputs.version }}
            3. Prepares for next development version ${{ github.event.inputs.next-version }}
            
            Please review and merge to complete the release process.
          labels: release