name: Release Parent POM

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
      next-version:
        description: 'Next development version (e.g., 1.0.1-SNAPSHOT)'
        required: true

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Prepare Next Version
        id: prepare-version
        run: |
          # Ensure next version ends with -SNAPSHOT
          NEXT_VERSION=${{ github.event.inputs.next-version }}
          if [[ ! $NEXT_VERSION == *-SNAPSHOT ]]; then
            NEXT_VERSION="${NEXT_VERSION}-SNAPSHOT"
          fi
          echo "next-version=${NEXT_VERSION}" >> $GITHUB_OUTPUT

      - name: Set Release Version
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.release-version }}
          mvn versions:commit

      - name: Verify Build
        run: mvn clean verify

      - name: Create Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<actions@github.com>"
          git add pom.xml
          git commit -m "Release version ${{ github.event.inputs.release-version }}"
          git tag -a v${{ github.event.inputs.release-version }} -m "Release version ${{ github.event.inputs.release-version }}"

      - name: Set Next Snapshot Version
        run: |
          mvn versions:set -DnewVersion=${{ steps.prepare-version.outputs.next-version }}
          mvn versions:commit

      - name: Commit Next Snapshot Version
        run: |
          git add pom.xml
          git commit -m "Prepare next development version ${{ steps.prepare-version.outputs.next-version }}"


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Prepare release ${{ github.event.inputs.release-version }}
          branch: release/v${{ github.event.inputs.release-version }}
          delete-branch: true
          base: main
          title: Release ${{ github.event.inputs.release-version }}
          body: |
            ## Release Preparation
            
            - Release version: ${{ github.event.inputs.release-version }}
            - Next development version: ${{ steps.prepare-version.outputs.next-version }}
